"""jjkdsadsa

Revision ID: 0222fb98fe87
Revises: 
Create Date: 2022-12-15 15:45:42.807249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0222fb98fe87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyCooking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantityProtion', sa.Numeric(), nullable=True),
    sa.Column('dataPreparation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailyCooking_dataPreparation'), 'dailyCooking', ['dataPreparation'], unique=False)
    op.create_index(op.f('ix_dailyCooking_id'), 'dailyCooking', ['id'], unique=False)
    op.create_index(op.f('ix_dailyCooking_quantityProtion'), 'dailyCooking', ['quantityProtion'], unique=False)
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameD', sa.String(), nullable=True),
    sa.Column('airD', sa.String(), nullable=True),
    sa.Column('weightD', sa.Numeric(), nullable=True),
    sa.Column('imgD', sa.Boolean(), nullable=True),
    sa.Column('dailyCooking_id', sa.Integer(), nullable=False),
    sa.Column('disProd_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dailyCooking_id'], ['dailyCooking.id'], ),
    sa.ForeignKeyConstraint(['disProd_id'], ['disprod.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dishes_airD'), 'dishes', ['airD'], unique=False)
    op.create_index(op.f('ix_dishes_id'), 'dishes', ['id'], unique=False)
    op.create_index(op.f('ix_dishes_imgD'), 'dishes', ['imgD'], unique=False)
    op.create_index(op.f('ix_dishes_nameD'), 'dishes', ['nameD'], unique=False)
    op.create_index(op.f('ix_dishes_weightD'), 'dishes', ['weightD'], unique=False)
    op.create_table('disprod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('dishes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dishes_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disprod_id'), 'disprod', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameP', sa.String(), nullable=True),
    sa.Column('calories', sa.Numeric(), nullable=True),
    sa.Column('weightP', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('disProd_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disProd_id'], ['disprod.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_calories'), 'product', ['calories'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_nameP'), 'product', ['nameP'], unique=False)
    op.create_index(op.f('ix_product_price'), 'product', ['price'], unique=False)
    op.create_index(op.f('ix_product_weightP'), 'product', ['weightP'], unique=False)
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeCookingD', sa.DateTime(), nullable=True),
    sa.Column('technologyCooking', sa.String(), nullable=True),
    sa.Column('dishes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dishes_id'], ['dishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_id'), 'prescription', ['id'], unique=False)
    op.create_index(op.f('ix_prescription_technologyCooking'), 'prescription', ['technologyCooking'], unique=False)
    op.create_index(op.f('ix_prescription_timeCookingD'), 'prescription', ['timeCookingD'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_timeCookingD'), table_name='prescription')
    op.drop_index(op.f('ix_prescription_technologyCooking'), table_name='prescription')
    op.drop_index(op.f('ix_prescription_id'), table_name='prescription')
    op.drop_table('prescription')
    op.drop_index(op.f('ix_product_weightP'), table_name='product')
    op.drop_index(op.f('ix_product_price'), table_name='product')
    op.drop_index(op.f('ix_product_nameP'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_calories'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_disprod_id'), table_name='disprod')
    op.drop_table('disprod')
    op.drop_index(op.f('ix_dishes_weightD'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_nameD'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_imgD'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_id'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_airD'), table_name='dishes')
    op.drop_table('dishes')
    op.drop_index(op.f('ix_dailyCooking_quantityProtion'), table_name='dailyCooking')
    op.drop_index(op.f('ix_dailyCooking_id'), table_name='dailyCooking')
    op.drop_index(op.f('ix_dailyCooking_dataPreparation'), table_name='dailyCooking')
    op.drop_table('dailyCooking')
    # ### end Alembic commands ###
